# Generated by Django 3.0.8 on 2020-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_input', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.DeleteModel(
            name='Endpoints',
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
